export const personsActionTypes = {
  SET_PERSONS: 'SET_PERSONS',
  GET_MORE_PERSONS: 'GET_MORE_PERSONS',
  LIKE_PERSON: 'LIKE_PERSON',
  EDIT_AVATAR: 'EDIE_AVATAR',
  CLEAR_PERSONS: 'CLEAR_PERSONS',
}
